[Interface]
PrivateKey = +Ew2/iKoX8ndSbhMcLlXbAcL7mw3ccaW4n0tcRgMNks=
Address = 10.0.0.2/24
DNS = 8.8.8.8, 1.1.1.1

[Peer]
PublicKey = GREllj0aZDLmFpcziI4hQ8o7qByPpLWgaGcWJdGnZGs=
Endpoint = 2.58.98.163:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
